import type { Metadata } from "next";
//import { Inter, Courier_Prime } from "next/font/google";
import localFont from 'next/font/local'
import "./globals.css";

//const inter = Inter({ subsets: ["latin"] });
//const courier = Courier_Prime({ weight: "400", subsets: ["latin-ext"] });
const myFont = localFont({ src: '../font/CascadiaCode.woff2' })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={myFont.className}>{children}</body>
    </html>
  );
}