import type { Metadata } from "next";
//import { Inter, Courier_Prime } from "next/font/google";
import localFont from 'next/font/local'
import "./globals.css";
import Topbar from "@/components/topbar";
import Sidebar from "@/components/sidebar";
import Terminal from "@/components/terminal";


//const inter = Inter({ subsets: ["latin"] });
//const courier = Courier_Prime({ weight: "400", subsets: ["latin-ext"] });
const myFont = localFont({ src: '../font/CascadiaCode.woff2' })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={myFont.className}>
        <div className="flex flex-col h-screen overflow-hidden">
          <Topbar />
          <div className="flex flex-1 overflow-hidden">
            <Sidebar />
            <div className="flex flex-col flex-1 overflow-hidden">
              {children}
              <Terminal className="h-1/3" />
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}